---

# The base pipeline that runs continuously, checks for branches and
# creates a new pipeline instance for each of them.

resource_types:
- name: gitea-pr
  type: registry-image
  source:
    repository: registry.local:5000/gitea-pr

resources:
- name: repo-pr
  type: gitea-pr
  source:
    access_token: ((gitea_api_key))
    owner: ((owner))
    repo: ((repo))
    url: https://git.sclu1034.dev
- name: repo
  type: git
  source:
    uri: https://git.sclu1034.dev/bitsquid_dt/dtmt
    # DEBUG:
    branch: feat/ci


jobs:
  - name: set-pipelines
    plan:
    - in_parallel:
      - get: repo-pr
        trigger: true
      - get: repo
    - load_var: prs
      file: repo-pr/prs.json
    - across:
      - var: pr
        values: ((.:prs))
      set_pipeline: dtmt-pr
      file: repo/.ci/pipelines/pr.yml
      vars:
        pr: ((.:pr))
        gitea_api_key: ((gitea_api_key))
      instance_vars:
        pr: ((.:pr.number))


