# yaml-language-server: $schema=https://raw.githubusercontent.com/cappyzawa/concourse-pipeline-jsonschema/master/concourse_jsonschema.json#/definitions/Config
---

# The actual CI pipeline that is run per branch
resource_types:
- name: gitea-package
  type: registry-image
  source:
    repository: registry.sclu1034.dev/gitea-package
    username: ((registry_user))
    password: ((registry_password))

- name: gitea-status
  type: registry-image
  source:
    repository: registry.sclu1034.dev/gitea-status
    username: ((registry_user))
    password: ((registry_password))


resources:
- name: repo
  type: git
  source:
    uri: https://git.sclu1034.dev/bitsquid_dt/dtmt
    branch: ((pr.head.ref))

- name: gitea-package
  type: gitea-package
  source:
    access_token: ((gitea_api_key))
    url: https://git.sclu1034.dev
    owner: bitsquid_dt
    type: generic
    name: dtmt

- name: pr-status-lint-clippy
  type: gitea-status
  source:
    access_token: ((gitea_api_key))
    url: https://git.sclu1034.dev
    owner: bitsquid_dt
    repo: dtmt
    context: lint/clippy
    description: Checking for common mistakes and opportunities for code improvement

- name: pr-status-build-msvc
  type: gitea-status
  source:
    access_token: ((gitea_api_key))
    url: https://git.sclu1034.dev
    owner: bitsquid_dt
    repo: dtmt
    context: build/msvc
    description: "Build for the target platform: msvc"

- name: pr-status-build-linux
  type: gitea-status
  source:
    access_token: ((gitea_api_key))
    url: https://git.sclu1034.dev
    owner: bitsquid_dt
    repo: dtmt
    context: build/linux
    description: "Build for the target platform: linux"


jobs:
- name: clippy
  on_success:
    put: state-success
    resource: pr-status-lint-clippy
    no_get: true
    params:
      state: success
      sha: ((.:git_sha))

  on_failure:
    put: state-failure
    resource: pr-status-lint-clippy
    no_get: true
    params:
      state: failure
      sha: ((.:git_sha))

  plan:
  - get: repo
    trigger: true

  - load_var: git_sha
    file: repo/.git/ref

  - put: state-pending
    resource: pr-status-lint-clippy
    no_get: true
    params:
      state: pending
      sha: ((.:git_sha))

  - task: check
    file: repo/.ci/tasks/clippy.yml
    vars:
      gitea_api_key: ((gitea_api_key))


- name: build-msvc
  on_success:
    put: state-success
    resource: pr-status-build-msvc
    no_get: true
    params:
      state: success
      sha: ((.:git_sha))

  on_failure:
    put: state-failure
    resource: pr-status-build-msvc
    no_get: true
    params:
      state: failure
      sha: ((.:git_sha))

  plan:
  - get: repo
    trigger: true

  - load_var: git_sha
    file: repo/.git/ref

  - put: state-pending
    resource: pr-status-build-msvc
    no_get: true
    params:
      state: pending
      sha: ((.:git_sha))

  - task: build
    file: repo/.ci/tasks/build.yml
    vars:
      target: msvc
      pr: ((pr))
      gitea_url: https://git.sclu1034.dev
      gitea_api_key: ((gitea_api_key))

  - load_var: version_number
    reveal: true
    file: artifact/version

  - put: package
    resource: gitea-package
    no_get: true
    inputs:
      - artifact
    params:
      version: ((.:version_number))
      fail_fast: true
      override: true
      globs:
        - artifact/dtmt
        - artifact/dtmm
        - artifact/*.exe
        - artifact/*.sha256

- name: build-linux
  on_success:
    put: state-success
    resource: pr-status-build-linux
    no_get: true
    params:
      state: success
      sha: ((.:git_sha))

  on_failure:
    put: state-failure
    resource: pr-status-build-linux
    no_get: true
    params:
      state: failure
      sha: ((.:git_sha))

  plan:
  - get: repo
    trigger: true

  - load_var: git_sha
    file: repo/.git/ref

  - put: state-pending
    resource: pr-status-build-linux
    no_get: true
    params:
      state: pending
      sha: ((.:git_sha))

  - task: build
    file: repo/.ci/tasks/build.yml
    vars:
      target: linux
      pr: ((pr))
      gitea_url: https://git.sclu1034.dev
      gitea_api_key: ((gitea_api_key))

  - load_var: version_number
    reveal: true
    file: artifact/version

  - put: package
    resource: gitea-package
    no_get: true
    inputs:
      - artifact
    params:
      version: ((.:version_number))
      fail_fast: true
      override: true
      globs:
        - artifact/dtmt
        - artifact/dtmm
        - artifact/*.exe
        - artifact/*.sha256

