# yaml-language-server: $schema=https://raw.githubusercontent.com/cappyzawa/concourse-pipeline-jsonschema/master/concourse_jsonschema.json#/definitions/Config
---

# The actual CI pipeline that is run per branch

resources:
- name: repo
  type: git
  source:
    uri: http://forgejo:3000/bitsquid_dt/dtmt
    branch: ((pr.head.ref))

jobs:
- name: clippy
  plan:
  - get: repo
    trigger: true
  - load_var: ref
    file: repo/.git/ref
  - task: check
    file: repo/.ci/tasks/clippy.yml
    vars:
      ref: ((.:ref))
      gitea_api_key: ((gitea_api_key))

- name: build-msvc
  plan:
  - get: repo
    trigger: true
  - load_var: ref
    file: repo/.git/ref
  - task: build
    file: repo/.ci/tasks/build.yml
    vars:
      target: msvc
      output: artifact
      ref: ((.:ref))
      gitea_url: http://forgejo:3000
      gitea_api_key: ((gitea_api_key))

- name: build-linux
  plan:
  - get: repo
    trigger: true
  - load_var: ref
    file: repo/.git/ref
  - task: build
    file: repo/.ci/tasks/build.yml
    vars:
      target: linux
      output: artifact
      ref: ((.:ref))
      gitea_url: http://forgejo:3000
      gitea_api_key: ((gitea_api_key))
  - task: upload
    file: repo/.ci/tasks/upload.yml
    vars:
      input: artifact
      pr: ((.:pr))
      gitea_api_key: ((gitea_api_key))
      gitea_user: bitsquid_dt
      gitea_url: http://forgejo:3000
