[workspace]
resolver = "2"
members = [
    "crates/dtmt",
    "crates/dtmm",
    "lib/dtmt-shared",
    "lib/oodle",
    "lib/sdk",
    "lib/serde_sjson",
    "lib/luajit2-sys",
]
exclude = ["lib/color-eyre"]

[patch.crates-io]
color-eyre = { path = "lib/color-eyre" }

[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
strip = "debuginfo"

# The MSVC toolchain cannot handle LTO properly. Some symbol related to
# panic unwind would always be missing.
# So we use a separate profile for when we can compile with LTO.
[profile.release-lto]
inherits = "release"
lto = true
