FROM rust:slim-bullseye

RUN set -eux; \
    apt-get update; \
    apt-get install --no-install-recommends -y \
        build-essential \
        curl \
        git \
        gpg \
        jq \
        libatk1.0-dev \
        libclang-13-dev \
        libglib2.0-dev \
        libgtk-3-dev \
        libpango1.0-dev \
        libssl-dev \
        libzstd-dev \
        pkg-config; \
    apt-get remove -y --auto-remove; \
    rm -rf /var/lib/apt/lists/*; \
    rustup default nightly

WORKDIR /src/dtmt

COPY lib/oodle/*.so lib/oodle/*.a /src/
