---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: registry.local:5000/dtmt-ci-base-((target))
    tag: latest

inputs:
- name: repo

outputs:
- name: ((output))

params:
  CI: true
  TARGET: ((target))
  GITEA_API_KEY: ((gitea_api_key))
  REF: ((ref))
  OUTPUT: ((output))

run:
  path: .ci/util/run.sh
  dir: repo
  args:
    - .ci/tasks/build.sh
    - build/((target))
    - "Build for the target platform: ((target))"
