# yaml-language-server: $schema=https://raw.githubusercontent.com/cappyzawa/concourse-pipeline-jsonschema/master/concourse_jsonschema.json#/definitions/TaskConfig
---
platform: linux

image_resource:
  name: ctmt-bi-base-((target))
  type: registry-image
  source:
    repository: registry.local:5000/dtmt-ci-base-((target))
    tag: latest

inputs:
- name: repo

outputs:
- name: artifact

caches:
  - path: repo/target
  - path: /usr/local/cargo/registry

params:
  CI: "true"
  TARGET: ((target))
  PR: ((pr))
  OUTPUT: artifact

run:
  path: repo/.ci/tasks/build.sh
