---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: registry.local:5000/dtmt-ci-base-linux
    tag: latest

inputs:
- name: repo

params:
  CI: true
  GITEA_API_KEY: ((gitea_api_key))
  REF: ((ref))

run:
  path: .ci/util/run.sh
  dir: repo
  args:
    - .ci/tasks/clippy.sh
    - lint/clippy
    - "Checking for common mistakes and opportunities for code improvement"

