# yaml-language-server: $schema=https://raw.githubusercontent.com/cappyzawa/concourse-pipeline-jsonschema/master/concourse_jsonschema.json#/definitions/TaskConfig
---
platform: linux

image_resource:
  name: dtmt-ci-base-linux
  type: registry-image
  source:
    repository: registry.local:5000/dtmt-ci-base-linux
    tag: latest

inputs:
- name: repo

caches:
  - path: repo/target
  - path: /usr/local/cargo/registry

params:
  CI: "true"
  GITEA_API_KEY: ((gitea_api_key))

run:
  path: .ci/tasks/clippy.sh
  dir: repo

