# yaml-language-server: $schema=https://raw.githubusercontent.com/cappyzawa/concourse-pipeline-jsonschema/master/concourse_jsonschema.json#/definitions/TaskConfig
---
platform: linux

image_resource:
  name: python-script
  type: registry-image
  source:
    repository: registry.local:5000/python-script
    tag: latest

inputs:
- name: repo
- name: ((input))

params:
  CI: "true"
  GITEA_API_KEY: ((gitea_api_key))
  GITEA_URL: ((gitea_url))
  GITEA_USER: ((user))
  PR: ((pr))

run:
  path: repo/.ci/tasks/upload.sh
