FROM dtmt-ci-base-linux

COPY . /src/dtmt
COPY --from=dtmt-ci-base-linux /src/*.lib /src/*.so /src/dtmt/lib/oodle/
RUN --mount=type=cache,id=cargo-registry,target=/cargo/registry \
    --mount=type=cache,id=cargo-target,target=/src/dtmt/target \
    cargo build --release --locked
