[package]
name = "sdk"
version = "0.3.0"
edition = "2024"

[dependencies]
async-recursion = { workspace = true }
bitflags = { workspace = true }
byteorder = { workspace = true }
color-eyre = { workspace = true }
csv-async = { workspace = true }
dxc = { workspace = true }
fastrand = { workspace = true }
flate2 = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
glob = { workspace = true }
luajit2-sys = { workspace = true }
nanorand = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
oodle = { workspace = true }
path-slash = { workspace = true }
pin-project-lite = { workspace = true }
serde = { workspace = true }
serde_sjson = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
tracing-error = { workspace = true }
